### ISSUE TITLE
"Cannot read property 'addLabels' of null" in instrumenting/db.js:123:34

### ISSUE THREAD

**Issue by SimonSimCity** [kschingiz/meteor-elastic-apm#31]
I just ran into the following error on my console using this package in version `2.2.4`:

```
Exception in setInterval callback: TypeError: Cannot read property 'addLabels' of null
    at closeSpan (packages/kschingiz:meteor-elastic-apm/instrumenting/db.js:123:34)
    at Cursor.fetch (packages/kschingiz:meteor-elastic-apm/instrumenting/db.js:169:11)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:445:81)
    at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)
    at hook.update (packages/mongo/collection.js:585:31)
    at hook.update (packages/cultofcoders:redis-oplog/lib/mongo/Mutator.js:97:37)
    at hook.update (packages/cultofcoders:redis-oplog/lib/mongo/extendMongoCollection.js:39:35)
    at hook.Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:213:19)
    at hook.<anonymous> (packages/kschingiz:meteor-elastic-apm/instrumenting/db.js:91:32)
    at AccountsServer._expireTokens (packages/accounts-base/accounts_server.js:1018:16)
    at accounts.expireTokenInterval.Meteor.setInterval (packages/accounts-base/accounts_server.js:1432:14)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24)
```

I've just quickly reported it here - I'll check it out later if someone else doesn't resolve it first.

**Comment by kschingiz** [comment]
@SimonSimCity 
Fixed in this PR: #32
